/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

 #include "stm32f411xx.h"

 int main(void){
     GPIO_Handle_t LED_0;
     LED_0.GPIOx = GPIOD;
     LED_0.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_15;
     LED_0.GPIO_PinConfig.GPIO_PinMode = GPIO_OUTPUT_MODE;
     LED_0.GPIO_PinConfig.GPIO_PinOPType = 0;
    //  HAL_GPIO_PeriClockControl(GPIOD, ENABLE);
     HAL_GPIO_Init(LED_0);
 
     while(true){
         HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_15);
         for(int i = 0; i < 500000; i++){
             // wait
         }
     }
     return 0;
 }
